version: '3.8'

services:
  nuxt_cms_app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production 
    container_name: nuxt_cms_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      VUE_APP_API_URL: http://13.214.183.18/api
    networks:
      - laravel_cms

networks:
  laravel_cms:
    driver: bridge
