services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
#        platform: linux/amd64
        image: laravel_cms
        container_name: laravel_cms_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel_cms

    db:
        image: mysql:8.0
        container_name: laravel_cms_db
        restart: unless-stopped
        ports:
            - ${MYSQL_PORT_EXTRA:-3306}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_MYSQL_USER}
            MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=2213 --group_concat_max_len=1000000
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - laravel_cms

    nginx:
        image: nginx:alpine
        container_name: laravel_cms_nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel_cms
#    phpmyadmin:
#      image: phpmyadmin/phpmyadmin:5.2
##      image: arm64v8/phpmyadmin
#      container_name: 'phpmyadmin'
#      environment:
#        PMA_HOST: db
#        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      ports:
#        - "8800:80"
#      depends_on:
#        - db
#      networks:
#        - laravel_cms
volumes:
  mysql_data:
networks:
  laravel_cms:
        driver: bridge
