#version: "3.7" # từ 2021 xóa dòng này, vì docker composer có thể tự nhận biết được
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
#        platform: linux/amd64
        image: laravel_cms
        container_name: laravel_cms_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel_cms

    db:
        image: mysql:8.0
        container_name: laravel_cms_db # dùng cho host trong .env của laravel
        restart: unless-stopped
        ports:
            - ${MYSQL_PORT_EXTRA:-3306}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Cho phép root không cần mật khẩu, và comment dòng MYSQL_ROOT_PASSWORD lại
#            MYSQL_USER: ${DB_MYSQL_USER}  #cấu hình DB_MYSQL_USER trong evn phải khác root , vì MySQL Docker image không cho phép cấu hình root thông qua MYSQL_USER, nếu muốn dùng tài khoản root thì bỏ qua MYSQL_USER ,
#            MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD} #tương tự với MYSQL_PASSWORD thì DB_MYSQL_PASSWORD không được là root vì root sử dụng ở MYSQL_ROOT_PASSWORD
            MYSQL_USER: ${DB_MYSQL_USER}
            MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
#            MYSQL_TCP_PORT: 3307 # Mặc định docker mysql trên container là 3306 ,thay đổi cổng mặc định của MySQL ở trong container từ 3306 sang 3307. Điều này cũng sẽ cấu hình MySQL để lắng nghe trên cổng 3307 bên trong container.
#        expose:
#          - 3307  #Mở cổng 3307 bên trong container để các container khác có thể kết nối trực tiếp, hoặc dùng cho file port của env laravel
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=2213 --group_concat_max_len=1000000
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - laravel_cms

    nginx:
        image: nginx:alpine
        container_name: laravel_cms_nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT_EXTRA:-8080}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel_cms
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.2
#      image: arm64v8/phpmyadmin
      container_name: 'phpmyadmin'
      environment:
        PMA_HOST: db #tên mà csdl mà phpmyadmin sẽ dụng, thường là tên service container của dịch vụ mà nó sẽ sử dụng
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      ports:
        - "8800:80"
      depends_on:
        - db  # đảm bảo rằng service container db được khởi động trước khi phpmyadmin khởi chạy.
      networks:
        - laravel_cms

networks:
  laravel_cms:
        driver: bridge
